version: "3"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: 3grit-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    extends:
      file: env.yaml
      service: config_node

  dev:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    image: 3grit-dev
    ports:
      - "7777:7777"
    volumes:
      - ./app:/app
    extends:
      file: env.yaml
      service: config_node

  nginx:
    build: ./nginx
    image: 3grit-nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /etc/localtime:/etc/localtime
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: "always"

  redis:
    build: ./redis
    image: 3grit-redis

  mongo:
    build: ./mongo
    image: 3grit-mongo

  postgres:
    build: ./postgres
    image: 3grit-postgres
    restart: always
    ports:
      - "5432:5432"